#!/usr/bin/env python3
"""Independent Python check of encode.lz using base64, binascii and urllib.

    python3 tools/reference.py batch FILE   -> the same lines `encode.lz batch FILE` prints
    python3 tools/reference.py inputs SEED  -> a corpus of encode and decode lines, valid and broken
Decoders here are made strict the way encode.lz is: a decode is valid only if the standard decoder accepts the text AND
re-encoding the result gives back exactly the same text (which also rejects non-zero padding bits and missing padding).
"""
import base64
import binascii
import random
import re
import sys
import urllib.parse

FORMATS = ["base64", "base64url", "base32", "hex", "url"]


def encode(fmt, data):
    if fmt == "base64":
        return base64.b64encode(data).decode()
    if fmt == "base64url":
        return base64.urlsafe_b64encode(data).decode()
    if fmt == "base32":
        return base64.b32encode(data).decode()
    if fmt == "hex":
        return data.hex()
    if fmt == "url":
        return urllib.parse.quote(data, safe="")
    raise ValueError(fmt)


def decode(fmt, text):
    """Returns bytes, or None if encode.lz must reject the text."""
    try:
        raw = text.encode("ascii")
    except UnicodeEncodeError:
        return None
    if fmt in ("base64", "base64url", "base32"):
        pattern = {"base64": r"[A-Za-z0-9+/=]*", "base64url": r"[A-Za-z0-9_=-]*", "base32": r"[A-Z2-7=]*"}[fmt]
        if not re.fullmatch(pattern, text):
            return None
        try:
            data = {"base64": base64.b64decode, "base64url": base64.urlsafe_b64decode, "base32": base64.b32decode}[fmt](raw)
        except (binascii.Error, ValueError):
            return None
        return data if encode(fmt, data) == text else None
    if fmt == "hex":
        return bytes.fromhex(text) if re.fullmatch(r"(?:[0-9a-fA-F]{2})*", text) else None
    if fmt == "url":
        if not re.fullmatch(r"(?:[^%]|%[0-9a-fA-F]{2})*", text):
            return None
        return urllib.parse.unquote_to_bytes(text)
    return None


def batch(path):
    n = 0
    for line in open(path, encoding="utf-8").read().split("\n"):
        if not line or line.startswith("#"):
            continue
        n += 1
        p1 = line.find(" ")
        p2 = line.find(" ", p1 + 1) if p1 >= 0 else -1
        if p1 < 0 or p2 < 0:
            print("%d error" % n)
            continue
        cmd, fmt, rest = line[:p1], line[p1 + 1:p2], line[p2 + 1:]
        out = "error"
        if fmt in FORMATS:
            if cmd == "encode":
                out = encode(fmt, rest.encode("utf-8"))
            elif cmd == "decode":
                d = decode(fmt, rest)
                out = "error" if d is None else d.hex()
        print("%d %s" % (n, out))


def inputs(seed):
    rng = random.Random(seed)
    alphabet = "abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,;:!?-_/\\'\"()[]{}<>@#$%^&*+=~`|éüñ日本語"
    lines = ["# generated by tools/reference.py inputs %d" % seed]
    texts = [""] + ["".join(rng.choice(alphabet) for _ in range(n)) for n in list(range(1, 25)) + [31, 32, 33, 60, 100, 250]]
    texts = [t for t in texts if not t.startswith("#")]
    for t in texts:
        for fmt in FORMATS:
            lines.append("encode %s %s" % (fmt, t))
    for t in texts:
        data = t.encode()
        for fmt in FORMATS:
            enc = encode(fmt, data)
            lines.append("decode %s %s" % (fmt, enc))
            if len(enc) > 2:
                broken = [enc[:-1], enc + "=", enc[:1] + "!" + enc[2:], enc + " ", " " + enc, enc.lower() if enc.lower() != enc else enc.upper(), enc.replace("=", "")]
                if fmt in ("base64", "base64url", "base32"):
                    i = rng.randrange(len(enc))
                    broken.append(enc[:i] + rng.choice("=0189+/-_") + enc[i + 1:])
                    broken.append(enc[:-2] + "==" if enc.endswith("=") else enc[:-2] + "A=")
                for b in rng.sample(broken, 3):
                    lines.append("decode %s %s" % (fmt, b))
    lines += ["decode base64 QQ==", "decode base64 QR==", "decode base64 QUI=", "decode base64 QUJ=", "decode base64 =AAA", "decode base64 AA=A", "decode base64 ====",
              "decode base32 ME======", "decode base32 MF======", "decode base32 MFRA====", "decode base32 MFRGG===", "decode base32 MFRGGZA=", "decode base32 MFRGGZDF",
              "decode hex 4A4b", "decode hex 4", "decode hex 4g", "decode hex 48 65", "decode url %41%42", "decode url %4", "decode url %zz", "decode url a+b", "decode url é",
              "encode nosuch abc", "frob base64 abc", "encode base64", "decode url a%2"]
    return "\n".join(lines)


if __name__ == "__main__":
    if sys.argv[1] == "batch":
        batch(sys.argv[2])
    else:
        print(inputs(int(sys.argv[2])))
